"""Airzone Cloud API constants."""

API_AUTH_LOGIN = "auth/login"
API_AUTH_REFRESH_TOKEN = "auth/refreshToken"
API_CONFIG = "config"
API_CONNECTION_DATE = "connection_date"
API_DEVICE_ID = "device_id"
API_DEVICE_TYPE = "device_type"
API_DEVICES = "devices"
API_DISCONNECTION_DATE = "disconnection_date"
API_EMAIL = "email"
API_INSTALLATION_ID = "installation_id"
API_INSTALLATIONS = "installations"
API_IS_CONNECTED = "isConnected"
API_NAME = "name"
API_PASSWORD = "password"
API_REFRESH_TOKEN = "refreshToken"
API_STAT_AP_MAC = "stat_ap_mac"
API_STAT_CHANNEL = "stat_channel"
API_STAT_QUALITY = "stat_quality"
API_STAT_SSID = "stat_ssid"
API_STATUS = "status"
API_SYSTEM_NUMBER = "system_number"
API_TOKEN = "token"
API_URL = "https://m.airzonecloud.com"
API_USER = "user"
API_USER_LOGOUT = "user/logout"
API_V1 = "api/v1"
API_WS = "ws"
API_WS_FW = "ws_fw"
API_WS_IDS = "ws_ids"
API_WS_TYPE = "ws_type"
API_ZONE_NUMBER = "zone_number"

API_AZ_SYSTEM = "az_system"
API_AZ_ZONE = "az_zone"

AZD_CONNECTED = "connected"
AZD_CONNECTION_DATE = "connection-date"
AZD_DISCONNECTION_DATE = "disconnection-date"
AZD_FIRMWARE = "firmware"
AZD_ID = "id"
AZD_INSTALLATION = "installation"
AZD_INSTALLATIONS = "installations"
AZD_NAME = "name"
AZD_SYSTEM = "system"
AZD_SYSTEMS = "systems"
AZD_TYPE = "type"
AZD_WEBSERVER = "web-server"
AZD_WEBSERVERS = "web-servers"
AZD_WIFI_CHANNEL = "wifi-channel"
AZD_WIFI_MAC = "wifi-mac"
AZD_WIFI_QUALITY = "wifi-quality"
AZD_WIFI_SSID = "wifi-ssid"
AZD_ZONE = "zone"
AZD_ZONES = "zones"

HEADER_AUTHORIZATION = "Authorization"
HEADER_BEARER = "Bearer"

HTTP_CALL_TIMEOUT = 10
